<a href="https://colab.research.google.com/github/Somrat390/NLP/blob/main/Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bag of Word Using Spam or non-spam email file

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(df['Message'],df['spam'], test_size=0.2, stratify=df['spam'])

In [ ]:
df.shape

(5572, 3)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train.shape

(4457,)

In [ ]:
y_train.shape

(4457,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59170 stored elements and shape (4457, 7677)>

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv.shape

(4457, 7677)

In [ ]:
v.get_feature_names_out()[7676:]

array(['〨ud'], dtype=object)

In [ ]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [ ]:
v.vocabulary_

{'nice': 4728,
 'wait': 7290,
 'should': 6052,
 'you': 7641,
 'be': 1278,
 'texting': 6726,
 'right': 5732,
 'now': 4798,
 'not': 4785,
 'gonna': 3157,
 'pay': 5068,
 'your': 7646,
 'ticket': 6822,
 'ya': 7600,
 'know': 3923,
 'heart': 3348,
 'is': 3714,
 'empty': 2565,
 'without': 7485,
 'love': 4191,
 'mind': 4443,
 'wisdom': 7471,
 'eyes': 2721,
 'dreams': 2425,
 'amp': 949,
 'life': 4062,
 'frnds': 2995,
 'so': 6210,
 'alwys': 932,
 'in': 3607,
 'touch': 6927,
 'good': 3158,
 'night': 4735,
 'sweet': 6583,
 'compliments': 1921,
 'to': 6867,
 'was': 7326,
 'away': 1177,
 'from': 3000,
 'the': 6747,
 'system': 6605,
 'how': 3489,
 'side': 6082,
 'nights': 4738,
 'we': 7350,
 'nt': 4803,
 'staying': 6386,
 'at': 1121,
 'port': 5271,
 'step': 6397,
 'liao': 4053,
 'too': 6905,
 'ex': 2672,
 'death': 2169,
 'if': 3566,
 'me': 4367,
 'leave': 4021,
 'note': 4786,
 'that': 6743,
 'says': 5876,
 'its': 3732,
 'all': 912,
 'robs': 5755,
 'fault': 2772,
 'avenge': 1166,
 'hey': 3390,
 'what': 7410,
 'happen': 3291,
 'de': 2159,
 'are': 1050,
 'alright': 922,
 'no': 4754,
 'nokia': 4763,
 'tone': 6893,
 'ur': 7135,
 'mob': 4502,
 'every': 2649,
 'week': 7372,
 'just': 3840,
 'txt': 7026,
 'nok': 4762,
 '87021': 688,
 '1st': 342,
 'free': 2965,
 'get': 3096,
 'txtin': 7031,
 'and': 961,
 'tell': 6686,
 'friends': 2987,
 '150p': 311,
 '16': 321,
 'reply': 5667,
 'hl': 3418,
 '4info': 531,
 'prakesh': 5319,
 'there': 6765,
 'up': 7117,
 'wan': 7308,
 'come': 1888,
 'then': 6759,
 'lor': 4169,
 'but': 1576,
 'din': 2297,
 'any': 993,
 'stripes': 6448,
 'skirt': 6137,
 'have': 3322,
 'been': 1300,
 'practising': 5316,
 'curtsey': 2093,
 'dear': 2165,
 'ok': 4870,
 'meet': 4385,
 'corporation': 1990,
 'st': 6349,
 'outside': 4976,
 'gap': 3055,
 'can': 1629,
 'see': 5927,
 'my': 4629,
 'working': 7526,
 'doing': 2375,
 'project': 5399,
 'frens': 2978,
 'nope': 4773,
 'going': 3148,
 'home': 3442,
 'go': 3137,
 'pump': 5441,
 'petrol': 5125,
 'like': 4073,
 'rain': 5500,
 'soon': 6248,
 'll': 4123,
 'before': 1305,
 'got': 3173,
 'it': 3724,
 'seventeen': 5980,
 'pounds': 5297,
 'for': 2923,
 'seven': 5979,
 'hundred': 3519,
 'ml': 4490,
 'hope': 3457,
 'two': 7024,
 'teams': 6669,
 'waiting': 7293,
 'some': 6223,
 'players': 5196,
 'oh': 4865,
 'fine': 2837,
 'by': 1589,
 'tonight': 6900,
 'many': 4309,
 'times': 6836,
 'told': 6880,
 'stage': 6354,
 'use': 7153,
 'laugh': 3991,
 'listen': 4105,
 'aha': 872,
 'where': 7421,
 'those': 6792,
 'need': 4687,
 'person': 5111,
 'give': 3121,
 'na': 4638,
 '2p': 424,
 'per': 5096,
 'min': 4441,
 'call': 1605,
 'germany': 3095,
 '08448350055': 64,
 'bt': 1542,
 'line': 4087,
 'check': 1745,
 'planettalkinstant': 5188,
 'com': 1883,
 'info': 3638,
 'text': 6719,
 'stop': 6418,
 'opt': 4921,
 'out': 4966,
 'romantic': 5766,
 'anytime': 1003,
 'best': 1332,
 'with': 7481,
 'looks': 4165,
 'scrumptious': 5903,
 'daddy': 2118,
 'wants': 7317,
 'eat': 2499,
 'long': 4156,
 'did': 2273,
 'stitch': 6410,
 'his': 3410,
 'trouser': 6979,
 'well': 7388,
 'others': 4956,
 'marry': 4325,
 'them': 6755,
 'video': 7217,
 'camera': 1626,
 'phones': 5142,
 'half': 3270,
 'price': 5361,
 'rental': 5653,
 '12': 283,
 'mths': 4589,
 '500': 547,
 'cross': 2057,
 'ntwk': 4807,
 'mins': 4454,
 '100': 261,
 'txts': 7034,
 'mobileupd8': 4508,
 '08001950382': 53,
 'or': 4927,
 'call2optout': 1607,
 '674': 591,
 'cool': 1983,
 'lt': 4212,
 'gt': 3227,
 'ish': 3716,
 'wnevr': 7501,
 'wana': 7310,
 'fal': 2743,
 'luv': 4229,
 'vth': 7268,
 'books': 1431,
 'bed': 1293,
 'fals': 2749,
 'yen': 7620,
 'madodu': 4268,
 'nav': 4671,
 'pretsorginta': 5354,
 'nammanna': 4651,
 'pretsovru': 5355,
 'important': 3597,
 'alwa': 930,
 'gud': 3231,
 'eveb': 2642,
 'talk': 6629,
 'sexy': 5984,
 'make': 4289,
 'new': 4717,
 'fall': 2745,
 'worlds': 7530,
 'most': 4552,
 'discreet': 2324,
 'dating': 2148,
 'service': 5970,
 'vip': 7233,
 '83110': 662,
 'who': 7429,
 'could': 2007,
 'of': 4846,
 'accenture': 774,
 'confirm': 1941,
 'true': 6982,
 'massages': 4332,
 'lots': 4179,
 'baby': 1199,
 'oil': 4868,
 'fave': 2774,
 'position': 5278,
 'tessy': 6713,
 'pls': 5210,
 'do': 2351,
 'favor': 2775,
 'convey': 1976,
 'birthday': 1371,
 'wishes': 7475,
 'nimya': 4744,
 'dnt': 2350,
 'forget': 2929,
 'today': 6871,
 'her': 3379,
 'shijas': 6020,
 'tomorrow': 6891,
 'send': 5950,
 'indians': 3630,
 'poor': 5263,
 'india': 3628,
 'country': 2013,
 'one': 4891,
 'swiss': 6593,
 'bank': 1223,
 'directors': 2311,
 'he': 3333,
 'lac': 3948,
 'crore': 2056,
 'indian': 3629,
 'money': 4529,
 'deposited': 2229,
 'banks': 1224,
 'which': 7425,
 'used': 7154,
 'taxless': 6654,
 'budget': 1550,
 'yrs': 7657,
 'jobs': 3796,
 'village': 7228,
 'delhi': 2207,
 'lane': 3969,
 'roads': 5751,
 'forever': 2926,
 'power': 5301,
 'suply': 6547,
 'more': 4544,
 'than': 6732,
 'social': 6212,
 'projects': 5400,
 'citizen': 1806,
 'monthly': 4538,
 'world': 7529,
 'imf': 3586,
 'loan': 4131,
 'think': 6779,
 'our': 4963,
 'blocked': 1392,
 'rich': 5729,
 'politicians': 5248,
 'full': 3019,
 'rights': 5735,
 'against': 860,
 'corrupt': 1995,
 'itna': 3730,
 'forward': 2946,
 'karo': 3863,
 'ki': 3888,
 'pura': 5448,
 'padhe': 5002,
 'gei': 3078,
 'happend': 3292,
 'tron': 6976,
 'maybe': 4361,
 'ill': 3577,
 'dl': 2345,
 '3d': 471,
 'when': 7417,
 'pansy': 5020,
 've': 7197,
 'living': 4120,
 'jungle': 3836,
 'years': 7614,
 'driving': 2438,
 'worried': 7532,
 'about': 758,
 '10': 260,
 'later': 3987,
 'mm': 4491,
 'asked': 1100,
 'radio': 5495,
 'meeting': 4387,
 'went': 7392,
 'hon': 3444,
 'lab': 3947,
 'had': 3258,
 'day': 2153,
 'mine': 4446,
 'really': 5558,
 'busy': 1575,
 'much': 4596,
 'don': 2384,
 'chat': 1738,
 '86688': 686,
 'let': 4046,
 'find': 2836,
 'each': 2482,
 'other': 4955,
 'only': 4897,
 'msg': 4578,
 'rcvd': 5537,
 'hg': 3392,
 'suite342': 6521,
 '2lands': 409,
 'row': 5780,
 'w1j6hl': 7274,
 'ldn': 4009,
 '18': 325,
 'over': 4982,
 'eerie': 2520,
 'tones': 6894,
 '4u': 541,
 'rply': 5785,
 'title': 6850,
 '8007': 639,
 'eg': 2525,
 'dracula': 2416,
 'titles': 6851,
 'ghost': 3107,
 'addamsfa': 810,
 'munsters': 4613,
 'exorcist': 2692,
 'twilight': 7021,
 'www': 7575,
 'getzed': 3105,
 'co': 1853,
 'uk': 7054,
 'pobox36504w45wq': 5228,
 'this': 6787,
 'receive': 5575,
 'something': 6232,
 'voice': 7253,
 'speaking': 6291,
 'expression': 2711,
 'childish': 1772,
 'naughty': 4669,
 'sentiment': 5961,
 'rowdy': 5781,
 'ful': 3017,
 'attitude': 1138,
 'shy': 6075,
 'attractive': 1139,
 'funny': 3028,
 'irritating': 3711,
 'lovable': 4190,
 'yup': 7664,
 'thanx': 6740,
 'black': 1377,
 'shirt': 6027,
 'blue': 1405,
 'jeans': 3773,
 'thk': 6788,
 'glad': 3125,
 'didn': 2275,
 'totally': 6925,
 'disagreeable': 2315,
 'lol': 4150,
 'am': 933,
 'office': 4856,
 'thank': 6734,
 'better': 1337,
 'work': 7523,
 'cause': 1686,
 'will': 7451,
 'feel': 2786,
 'otherwise': 4957,
 'number': 4812,
 'sure': 6556,
 'thing': 6777,
 'big': 1353,
 'man': 4298,
 'hockey': 3430,
 'elections': 2544,
 'shouldn': 6054,
 'on': 4888,
 'longer': 4157,
 'an': 957,
 'hour': 3481,
 'though': 6795,
 'phone': 5138,
 'die': 2278,
 'stay': 6383,
 'here': 3380,
 'finally': 2833,
 'has': 3308,
 'happened': 3293,
 'aftr': 857,
 'decades': 2172,
 'beer': 1302,
 'cheaper': 1741,
 'goverment': 3181,
 'expects': 2697,
 'us': 7149,
 'drink': 2430,
 'drive': 2435,
 'urgh': 7141,
 'coach': 1854,
 'hot': 3475,
 'smells': 6179,
 'chip': 1785,
 'fat': 2767,
 'thanks': 6735,
 'again': 859,
 'especially': 2626,
 'duvet': 2476,
 'predictive': 5330,
 'word': 7521,
 'sad': 5819,
 'story': 6430,
 'last': 3982,
 'wife': 7444,
 'wish': 7473,
 'parents': 5033,
 'forgot': 2934,
 'kids': 3895,
 'even': 2643,
 'colleagues': 1873,
 'as': 1089,
 'entered': 2591,
 'cabin': 1594,
 'pa': 4996,
 'said': 5827,
 'happy': 3301,
 'boss': 1442,
 'felt': 2796,
 'special': 6292,
 'she': 6008,
 'askd': 1099,
 'lunch': 4224,
 'after': 852,
 'invited': 3692,
 'apartment': 1009,
 'into': 3682,
 'bedroom': 1297,
 'minute': 4457,
 'sed': 5926,
 'mood': 4541,
 'came': 1625,
 'minuts': 4459,
 'latr': 3990,
 'wid': 7441,
 'cake': 1597,
 'kidz': 3896,
 'screaming': 5900,
 'surprise': 6563,
 'sofa': 6213,
 'naked': 4644,
 'remember': 5634,
 'yet': 7627,
 'still': 6408,
 'trying': 6992,
 'hold': 3433,
 'him': 3403,
 'want': 7313,
 'stuffs': 6472,
 'ke': 3870,
 'qi': 5467,
 'bored': 1437,
 'izzit': 3742,
 'suddenly': 6507,
 'pete': 5122,
 'jenny': 3777,
 'college': 1878,
 'leanne': 4016,
 'eng': 2576,
 'rocking': 5757,
 'ashes': 1093,
 'okay': 4871,
 'seen': 5933,
 'pick': 5151,
 'friday': 2983,
 'entry': 2601,
 'weekly': 7376,
 'comp': 1902,
 'chance': 1717,
 'win': 7454,
 'ipod': 3704,
 'pod': 5238,
 '80182': 644,
 'std': 6388,
 'rate': 5525,
 'apply': 1026,
 '08452810073': 69,
 'details': 2247,
 'plan': 5185,
 'valentines': 7178,
 'url': 7145,
 'sleep': 6147,
 'havent': 3325,
 'stuck': 6459,
 'orchard': 4934,
 'dad': 2117,
 'car': 1646,
 'dinner': 2303,
 'leh': 4033,
 'they': 6773,
 'time': 6835,
 'ring': 5737,
 'comes': 1890,
 'guys': 3247,
 'costumes': 2004,
 'gift': 3109,
 'their': 6753,
 'future': 3033,
 'yowifes': 7654,
 'hint': 3406,
 'wk': 7490,
 'gr8': 3185,
 'str8': 6432,
 'classic': 1816,
 'hit': 3412,
 'polys': 5256,
 'poly': 5250,
 '200p': 361,
 'does': 2362,
 'bb': 1261,
 'aight': 879,
 'cash': 1672,
 'plm': 5208,
 'da': 2113,
 'way': 7346,
 'ew': 2671,
 'noooooooo': 4772,
 'please': 5202,
 'stress': 6439,
 'once': 4890,
 'fair': 2739,
 'always': 931,
 'putting': 5460,
 'business': 1573,
 'put': 5457,
 'pictures': 5158,
 'ass': 1108,
 'facebook': 2725,
 'open': 4907,
 'people': 5094,
 'ever': 2648,
 'met': 4425,
 'why': 7437,
 'would': 7544,
 'picture': 5157,
 'room': 5769,
 'hurt': 3529,
 'violated': 7230,
 'take': 6622,
 'lead': 4012,
 'town': 6933,
 'stressfull': 6441,
 'may': 4359,
 'add': 809,
 'surely': 6557,
 'adds': 816,
 'ni8': 4726,
 'swt': 6597,
 'ringtone': 5740,
 'club': 1839,
 'direct': 2308,
 'mobile': 4504,
 'jay': 3766,
 'getting': 3104,
 'impatient': 3594,
 'belligerent': 1320,
 'morning': 4548,
 'repair': 5657,
 'shop': 6041,
 'reason': 5563,
 'aathi': 747,
 'tagged': 6616,
 'seemed': 5931,
 'count': 2010,
 'spook': 6325,
 'halloween': 3275,
 'collection': 1877,
 'logo': 4146,
 'pic': 5150,
 'message': 4418,
 'plus': 5214,
 'card': 1647,
 'zed': 7670,
 '08701417012150p': 77,
 'lacking': 3949,
 'particular': 5040,
 'dramastorm': 2418,
 'part': 5039,
 'worrying': 7535,
 'appt': 1038,
 'shame': 5995,
 'missed': 4470,
 'girls': 3118,
 'quizzes': 5488,
 'popcorn': 5266,
 'hair': 3265,
 'bus': 1570,
 'safe': 5822,
 'trip': 6971,
 'nigeria': 4733,
 'happiness': 3300,
 'very': 7209,
 'company': 1904,
 'share': 6001,
 'moments': 4525,
 'hmm': 3423,
 'chikku': 1770,
 'nyt': 4826,
 'save': 5868,
 'wedding': 7365,
 'lingerie': 4091,
 'bridal': 1503,
 'petticoatdreams': 5126,
 'choose': 1790,
 'superb': 6544,
 'selection': 5940,
 'national': 4664,
 'delivery': 2211,
 'brought': 1529,
 'weddingfriend': 7366,
 'else': 2548,
 'instead': 3666,
 'easy': 2498,
 'ah': 871,
 'sen': 5949,
 'selected': 5939,
 'means': 4373,
 'giggle': 3111,
 'saw': 5872,
 'possibly': 5285,
 'first': 2854,
 'person2die': 5112,
 'nvq': 4820,
 'prevent': 5357,
 'dehydration': 2201,
 'giving': 3124,
 'enough': 2589,
 'fluids': 2894,
 '2morro': 413,
 'masters': 4335,
 'sir': 6113,
 'everything': 2658,
 'dont': 2387,
 'dehydrated': 2200,
 'wasn': 7327,
 'babe': 1196,
 'swollen': 6595,
 'glands': 3126,
 'throat': 6804,
 'end': 2567,
 'match': 4337,
 'started': 6371,
 'sorry': 6257,
 'miles': 4437,
 'smiles': 6184,
 'made': 4267,
 'frm': 2992,
 'same': 5841,
 'letters': 4049,
 'difference': 2285,
 'smile': 6182,
 'face': 2724,
 'keeps': 3873,
 'keep': 3871,
 'smiling': 6186,
 'themob': 6758,
 'newest': 4719,
 'content': 1967,
 'games': 3051,
 'gossip': 3172,
 'babes': 1197,
 'sport': 6328,
 'fit': 2858,
 'funky': 3027,
 'wap': 7318,
 '82468': 659,
 'hi': 3394,
 'darlin': 2137,
 'trouble': 6977,
 'ijust': 3573,
 'talked': 6631,
 'mum': 4606,
 'im': 3581,
 'goin': 3146,
 'congratulations': 1949,
 'friend': 2986,
 'won': 7510,
 '000': 1,
 'xmas': 7585,
 'prize': 5376,
 'claim': 1808,
 '08718726971': 147,
 '10p': 272,
 'wnt': 7502,
 'buy': 1579,
 'bmw': 1409,
 'urgently': 7140,
 'vry': 7266,
 'urgent': 7139,
 'hv': 3534,
 'shortage': 6046,
 'lacs': 3950,
 'source': 6272,
 'arng': 1070,
 'dis': 2314,
 'amt': 954,
 'thats': 6746,
 'prob': 5380,
 'tot': 6923,
 'cos': 1997,
 'darren': 2140,
 'say': 5873,
 'shopping': 6043,
 'course': 2018,
 'wat': 7332,
 'jus': 3839,
 'sim': 6096,
 'lim': 4081,
 'look': 4160,
 'mp3': 4571,
 'player': 5195,
 'aiyah': 887,
 'already': 921,
 'lar': 3977,
 'nydc': 4825,
 'wheellock': 7416,
 'awake': 1174,
 'snow': 6207,
 'sing': 6105,
 'hu': 3505,
 'also': 924,
 'someone': 6227,
 'female': 2797,
 'place': 5180,
 'preferably': 5332,
 'smart': 6173,
 'help': 3368,
 'navigate': 4672,
 'through': 6805,
 'things': 6778,
 'choosing': 1791,
 'require': 5676,
 'guidance': 3237,
 'doubt': 2404,
 'ask': 1098,
 'outta': 4979,
 'congrats': 1947,
 'mobs': 4510,
 '2u': 430,
 'breathe1': 1499,
 'crazyin': 2040,
 'sleepingwith': 6150,
 'finest': 2838,
 'ymca': 7635,
 'pobox365o4w45wq': 5229,
 '300p': 443,
 'finish': 2840,
 'bath': 1251,
 'btw': 1544,
 'regarding': 5612,
 'try': 6990,
 'anyone': 997,
 '4th': 537,
 'guy': 3246,
 'commit': 1898,
 'random': 5516,
 'dude': 2461,
 'care': 1651,
 'financial': 2835,
 'problem': 5382,
 'seriously': 5968,
 'spell': 6300,
 'name': 4646,
 'princess': 5366,
 'sounds': 6269,
 'posted': 5289,
 'probs': 5386,
 'doinat': 2374,
 'mo': 4500,
 'sending': 5952,
 'greetings': 3213,
 'joy': 3821,
 'evening': 2644,
 'licks': 4058,
 'center': 1704,
 'tootsie': 6912,
 'pop': 5265,
 'ouch': 4962,
 'stayed': 6384,
 'bit': 1373,
 'salam': 5830,
 'alaikkum': 895,
 'pride': 5362,
 'pleasure': 5205,
 'tea': 6662,
 'pleased': 5203,
 'contact': 1963,
 'qatar': 5464,
 'rakhesh': 5510,
 'respectful': 5691,
 'regards': 5613,
 'training': 6942,
 'pool': 5261,
 'together': 6874,
 'bunch': 1561,
 'lotto': 4183,
 'tickets': 6823,
 'deal': 2161,
 'lucky': 4219,
 'winner': 7464,
 '88600': 703,
 '1million': 340,
 'ppt150x3': 5308,
 'normal': 4778,
 'box403': 1465,
 'w1t1jy': 7276,
 'complain': 1910,
 'num': 4811,
 'bettr': 1339,
 'directly': 2309,
 'bsnl': 1540,
 'offc': 4848,
 'nd': 4675,
 'guaranteed': 3229,
 '1000': 262,
 '2000': 355,
 'yr': 7656,
 'customer': 2098,
 'representative': 5672,
 '08714712394': 122,
 'between': 1340,
 '10am': 270,
 '7pm': 631,
 'nite': 4748,
 'pocay': 5234,
 'wocay': 7504,
 '4eva': 524,
 'promise': 5402,
 '2morrowxxxx': 415,
 'performance': 5101,
 'award': 1175,
 'calculated': 1600,
 'month': 4537,
 'current': 2090,
 'period': 5105,
 'gorgeous': 3170,
 'squishy': 6345,
 'mwahs': 4628,
 'remind': 5639,
 'shall': 5994,
 'test': 6714,
 'earlier': 2485,
 'appreciate': 1030,
 'weird': 7381,
 'supposed': 6552,
 'happening': 3295,
 'idea': 3558,
 'pub': 5434,
 'anybody': 994,
 'asks': 1103,
 'abt': 765,
 'tel': 6681,
 'search': 5910,
 'called': 1612,
 'falling': 2747,
 'bcoz': 1272,
 'force': 2924,
 'yourself': 7651,
 'smeone': 6180,
 'bslvyl': 1539,
 'leaving': 4023,
 'house': 3484,
 'film': 2827,
 '2day': 395,
 '6pm': 608,
 'dunno': 2470,
 'next': 4724,
 'show': 6058,
 'aft': 851,
 '850': 678,
 'toa': 6868,
 'payoh': 5076,
 '650': 589,
 'youdoing': 7642,
 'sar': 5850,
 'xxx': 7591,
 'li': 4052,
 'hai': 3263,
 'lecturer': 4026,
 'repeating': 5660,
 'weeks': 7377,
 'stuff': 6468,
 'waste': 7329,
 'brother': 1527,
 'alert': 900,
 'computer': 1926,
 '10k': 271,
 '150': 309,
 'voucher': 7263,
 '09064018838': 216,
 'ntt': 4806,
 'po': 5219,
 'box': 1455,
 'cro1327': 2055,
 'landline': 3964,
 'cost': 1999,
 '150ppm': 315,
 'mobiles': 4505,
 'vary': 7191,
 'ready': 5549,
 'settled': 5977,
 'lets': 4047,
 'laptop': 3976,
 'nan': 4653,
 'sonathaya': 6241,
 'soladha': 6218,
 'afternoon': 854,
 'sunshine': 6540,
 'dawns': 2152,
 'refreshed': 5608,
 'alive': 911,
 'breathe': 1498,
 'air': 882,
 'anything': 1001,
 'drastic': 2420,
 'dare': 2132,
 'sell': 5944,
 'pc': 5078,
 'actually': 806,
 'while': 7426,
 'spoke': 6322,
 ...}

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv,y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.97      0.91      0.94       149

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.97      0.91      0.94       149

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115